# vllm bench serve启动配置
base_config:
  base_url: "http://127.0.0.1:8080"  # 模型服务地址
  params:
    test_01:
      dataset-name: random
      max-concurrency: [ 1, 2, 4, 8, 10, 16, 32, 64, 80, 128 ]
      num-prompts: [ 320 ]
      random-input-len: [ 10240 ]
      random-output-len: [ 256 ]
    test_02:
      dataset-name: random
      max-concurrency: [ 1 ]
      num-prompts: [ 100 ]
      random-input-len: [ 194560 ]
      random-output-len: [ 1024 ]
    test_03:
      dataset-name: random
      max-concurrency: [ 1, 2, 4, 8, 10 ]
      num-prompts: [ 100 ]
      random-input-len: [ 194560 ]
      random-output-len: [ 1024 ]
    test_04:
      dataset-name: random
      max-concurrency: [ 128, 200 ]
      num-prompts: [ 1024 ]
      random-input-len: [ 10240 ]
      random-output-len: [ 1024 ]
    test_05:
      dataset-name: random
      max-concurrency: [ 32, 64 ]
      num-prompts: [ 1000 ]
      random-input-len: [ 90000 ]
      random-output-len: [ 2000 ]
    test_06:
      dataset-name: random
      max-concurrency: [ 1, 2, 4, 8, 16, 32, 64, 80, 128 ]
      num-prompts: [ 300 ]
      random-input-len: [ 70000 ]
      random-output-len: [ 1500 ]
  temperature: 0.7
  seed: 123
  ready-check-timeout-sec: 30

models:
  hygon_bw1000:
  - name: "minimax-m2.5"
    served-model-name: "minimax-m2.5"
    model_path: "/data/models/MiniMax-M2.5-bf16"
  - name: "qwen3.5"
    served-model-name: "qwen3.5"
    model_path: "/data/models/Qwen3.5-397B-A17B"
  kunlun_p800:
  - name: "MiniMax2.5"
    served-model-name: "MiniMax2.5"
    model_path: "/data/MiniMax-M2.5-W8A8-INT8-Dynamic"
  nvidia_h100:
  - name: "minimax-m2.5"
    served-model-name: "minimax-m2.5"
    model_path: "/userdata/llms/MiniMax/MiniMax-M2.5"

# vLLM 版本
#vllm_version: "0.17.0"  # 如 "0.17.0"
vllm_version: "0.15.1"  # 如 "0.17.0"
